# with readiness probes
# apiVersion: extensions/v1beta1 # for older API controllers
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: probes
  name: probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probes
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: probes
    spec:
      containers:
      - image: embano1/probes:2.0
        # imagePullPolicy: IfNotPresent # consider using this if image is stable
        imagePullPolicy: Always
        name: probes
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 2
        env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
